### ISSUE TITLE
[Feat] fcm token 저장 API 설계 및 기타 수정

### ISSUE THREAD

**Issue by Ji-Un-Gil** [Central-MakeUs/BlueClub-Server#106]
## Description 🖊️
- 로그인 시 이외에, 앱을 켤 때 fcm token 저장 필요
- #103 누락된 response field 추가
- delete API response field 통일 (204 X)
## To-do 🧑‍💻
- [ ] fcm token 저장 API 설계
- [ ] 날짜로 근무기록 조회 시 response >> diaryId 추가
- [ ] delete API http status 204 >> 200
- [ ] 회원탈퇴 권한 수정

## ETC ➕
