### ISSUE TITLE
[Feat] 날짜 형식 validation 추가 및 근무 기록 로직 통일

### ISSUE THREAD

**Issue by Ji-Un-Gil** [Central-MakeUs/BlueClub-Server#112]
## Description 🖊️
- 날짜 형식에 대해 커스텀 어노테이션으로 valid 판단
- 날짜 형식이 yyyy-M-d 와 같이 들어와도 yyyy-MM-dd로 정상적용되도록 변경
- #89 To-do 3, 적용된 GET /list/{yearMonth} API 외에 모든 근무 기록 관련해 해당 기준 적용하기로 결정
## To-do 🧑‍💻
- [ ] 날짜 형식 valid annotation
- [ ] GET /record/{yearMonth} API 에도 해당 로직 적용
- [ ] to-do list3

## ETC ➕
