### ISSUE TITLE
[Fix] 누락된 request 띄어쓰기 정책 통일 및 예외 처리

### ISSUE THREAD

**Issue by Ji-Un-Gil** [Central-MakeUs/BlueClub-Server#115]
## Description 🖊️
- Diary 관련 get API에서 request로 받은 job의 띄어쓰기 허용 정책 미적용 문제
- 일부 API들의 예외 미처리
- 다른 사용자의 근무 일지를 확인할 수 있는 문제
- 이메일 중복 정책 파기
## To-do 🧑‍💻
- [ ] job 띄어쓰기 허용하는 로직 추가
- [ ] 사용자 정보 추가 및 수정 시 닉네임 중복 예외 추가
- [ ] 다른 사용자의 근무 일지를 확인할 수 없도록 누락된 쿼리 수정
- [ ] 이메일 중복 정책 파기

## ETC ➕
