### ISSUE TITLE
[Feat] 회원가입 관련 로직 추가

### ISSUE THREAD

**Issue by Ji-Un-Gil** [Central-MakeUs/BlueClub-Server#22]
## Description 🖊️
- 논의 후 결정된 "수집할 개인정보" 및 플로우 바탕으로 관련 로직 추가
## To-do 🧑‍💻
- [ ] 네이버 OAuth scope 및 관련 로직 추가
- [ ] User Entity attribute 수정
- [ ] 소셜 회원가입 후 User 추가 정보 작성 API

## ETC ➕
