### ISSUE TITLE
[Chore] 회원 변경사항 적용

### ISSUE THREAD

**Issue by Ji-Un-Gil** [Central-MakeUs/BlueClub-Server#49]
## Description 🖊️
- 회원 관련 변경된 사항 적용 및 배포 간 불필요한 코드 제거
## To-do 🧑‍💻
- [ ] User Entity 변경사항
- [ ] Auth, User 로직 변경사항
- [ ] 기존 엔티티 및 로직 변경에 따른 테스트코드 수정
- [ ] Swagger 수정
## ETC ➕
