### ISSUE TITLE
[Feat] 월 총 기록 및 연속 기록 정보를 받는 API 설계 및 일부 API 수정

### ISSUE THREAD

**Issue by Ji-Un-Gil** [Central-MakeUs/BlueClub-Server#83]
## Description 🖊️
- 이번달 기록 개수 및 n일 연속 기록 정보를 받는 API
- 달성률 쪽 정보 받아올 때(GET /monthly_goal/{yearMonth}) response에 달성 수입 누락
- 유저 정보 업데이트 시 image 업로드하는 API, 유저정보 업데이트하는 API 분리
## To-do 🧑‍💻
- [ ] 추가 API 설계
- [ ] response가 일부 누락된 API 수정
- [ ] 프론트 요청에 따른 일부 API 분리

## ETC ➕
