### ISSUE TITLE
[Feat] 누락된 기능 설계 및 Swagger 수정

### ISSUE THREAD

**Issue by Ji-Un-Gil** [Central-MakeUs/BlueClub-Server#86]
## Description 🖊️
- 근무 형태 휴무 시 로직 수정
- API별 허용 권한 설정 누락
- GET 알림설정 API 누락
- 월 근무 기록 조회 API 등 누락된 상황별 response 추가
## To-do 🧑‍💻
- [ ] 근무 형태 휴무 시 로직 수정
- [ ] API별 허용 권한 설정
- [ ] GET 알림설정 API
- [ ] 누락된 상황별 response 추가

## ETC ➕
