### ISSUE TITLE
[Feat] 플로우 상 잘못된 로직 및 API 수정

### ISSUE THREAD

**Issue by Ji-Un-Gil** [Central-MakeUs/BlueClub-Server#89]
## Description 🖊️
- 프론트와의 회의 후, 프론트 측 요청 및 누락된 case 추가
## To-do 🧑‍💻
- [ ] iOS 이메일 미작성으로 인한 로그인 문제 해결
- [ ] 근무일지 캘린더/리스트 API 통합
- [ ] 근무일지 리스트 조회 시 사용자의 현재 직업 기준으로 작성된 근무일지만 가져오도록 쿼리 수정
- [ ] 홈 배너 이미지 리스트 조회 API 설계
- [ ] AccessToken 기한 수정
- [ ] MonthlyGoal 첫 사용자 예외 처리 >> Default value 전송
- [ ] 회원 추가정보 작성 시 pushAgree 필드 포함
- [ ] 기존 사용자의 정보 수정을 위한 닉네임 중복체크 시 본인 닉네임도 중복으로 처리되는 문제 수정

## ETC ➕
